stages:
  - build
  - push
  - deploy

cache:
  paths:
    - .cache/pip

build:
  stage: build
  only:
    - dev
  tags:
    - api-gw
  script:
    - ls
    - echo APP_NAME=$APP_NAME >> .env
    - echo MONGO_HOST=$MONGO_HOST >> .env
    - echo MONGO_DB=$MONGO_DB >> .env
    - echo MONGO_PORT=$MONGO_PORT >> .env
    - echo MONGO_USER=$MONGO_USER >> .env
    - echo MONGO_PASS=$MONGO_PASS >> .env
    - echo RABBIT_HOST=$RABBIT_HOST >> .env
    - echo RABBIT_PORT=$RABBIT_PORT >> .env
    - echo RABBIT_USER=$RABBIT_USER >> .env
    - echo RABBIT_PASS=$RABBIT_PASS >> .env
#    - docker login nexus.aasood.com -u registry -p $REGPASS 
    - docker build -t basket:0.0.1 .

dev_deploy:
  stage: deploy
  only:
    - dev
  tags:
    - api-gw
  script:
    - echo APP_NAME=$APP_NAME >> .env
    - echo MONGO_HOST=$MONGO_HOST >> .env
    - echo MONGO_DB=$MONGO_DB >> .env
    - echo MONGO_PORT=$MONGO_PORT >> .env
    - echo MONGO_USER=$MONGO_USER >> .env
    - echo MONGO_PASS=$MONGO_PASS >> .env
    - echo RABBIT_HOST=$RABBIT_HOST >> .env
    - echo RABBIT_PORT=$RABBIT_PORT >> .env
    - echo RABBIT_USER=$RABBIT_USER >> .env
    - echo RABBIT_PASS=$RABBIT_PASS >> .env
#    - docker login nexus.aasood.com -u registry -p $REGPASS
    - docker-compose -f docker-compose.yaml up -d --build

push:
  stage: push
  only:
    - master
  tags:
    - deploy
  script:
    - echo APP_NAME=$APP_NAME >> .env
    - echo MONGO_HOST="172.16.16.16" >> .env
    - echo MONGO_PORT=$MONGO_PORT >> .env
    - echo MONGO_USER=$MONGO_USER >> .env
    - echo MONGO_PASS=$MONGO_PASS >> .env
    - echo RABBIT_HOST="172.16.16.16" >> .env
    - echo RABBIT_PORT=$RABBIT_PORT >> .env
    - echo RABBIT_USER=$RABBIT_USER >> .env
    - echo RABBIT_PASS=$RABBIT_PASS >> .env
#    - docker login nexus.aasood.com -u registry -p $REGPASS
    - docker build -t basket:0.0.1 . #-t nexus.aasood.com/backend/basket:$CI_COMMIT_SHORT_SHA
#    - docker push nexus.aasood.com/backend/basket:$CI_COMMIT_SHORT_SHA

master_deploy:
  stage: deploy
  only:
    - master
  tags:
    - deploy
  script:
    - echo APP_NAME=$APP_NAME >> .env
    - echo MONGO_HOST="172.16.16.16" >> .env
    - echo MONGO_PORT=$MONGO_PORT >> .env
    - echo MONGO_USER=$MONGO_USER >> .env
    - echo MONGO_PASS=$MONGO_PASS >> .env
    - echo RABBIT_HOST="172.16.16.16" >> .env
    - echo RABBIT_PORT=$RABBIT_PORT >> .env
    - echo RABBIT_USER=$RABBIT_USER >> .env
    - echo RABBIT_PASS=$RABBIT_PASS >> .env
#    - docker login nexus.aasood.com -u registry -p $REGPASS
    - docker-compose -f docker-compose.yaml up -d --build
